# Generated by Django 2.2.5 on 2019-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.CharField(max_length=256, null=True, verbose_name='GitHub Page'),
        ),
    ]
