# Generated by Django 2.2.5 on 2019-10-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_team_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dosya',
            new_name='file_url',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='indweight',
            new_name='ind_weight',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='projectmembers',
            new_name='project_members',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='teamweight',
            new_name='team_weight',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting for approval'), (2, 'Working on it'), (3, 'Waiting for review'), (4, 'Rejected'), (5, 'Accepted')], default=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='team',
            name='github',
            field=models.CharField(max_length=256, null=True, verbose_name='Git Page'),
        ),
    ]
