# Generated by Django 3.0.3 on 2020-03-02 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20191001_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='project_members',
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_students',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Number of Students'),
        ),
        migrations.AddField(
            model_name='task',
            name='no_of_votes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Number of Votes'),
        ),
        migrations.AddField(
            model_name='task',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Is valid'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Team size'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
