# Generated by Django 3.1.4 on 2021-03-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201228_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopersTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.developer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.team')),
            ],
            options={
                'unique_together': {('developer', 'team')},
            },
        ),
    ]
