# Generated by Django 3.0.3 on 2020-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200302_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.CharField(max_length=256, verbose_name='creator'),
        ),
    ]
