# Generated by Django 3.1.4 on 2021-03-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_developersteams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevelopersTeams',
            new_name='DeveloperTeam',
        ),
    ]
