# Generated by Django 3.0.2 on 2020-03-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20200302_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='no_of_votes',
        ),
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting for approval'), (2, 'Working on it'), (3, 'Waiting for review'), (4, 'Rejected'), (5, 'Accepted')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Is Valid'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(1, 'Task Creation Accepted'), (2, 'Task Creation Rejected'), (3, 'Task Submission Accepted'), (4, 'Task Submission Rejected')], verbose_name='Vote Type')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Task')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
