# Generated by Django 3.1.4 on 2021-03-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210116_1424'),
    ]

    operations = [
    ]
