# Generated by Django 3.1.4 on 2021-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment_addfields_vote_alterfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isfinal',
            field=models.BooleanField(default=False),
        ),
    ]
