# Generated by Django 3.1.7 on 2021-04-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_model_rename_and_str_function_addition'),
        ('tasks', '0007_comment_isfinal'),
    ]

    operations = [
    ]
