# Generated by Django 3.0.2 on 2020-03-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200303_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Task Creation Accepted'), (2, 'Task Creation Rejected'), (3, 'Task Submission Accepted'), (4, 'Task Submission Rejected')], verbose_name='Vote Type'),
        ),
    ]
