# Generated by Django 3.1.4 on 2021-03-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201228_1220'),
        ('tasks', '0007_comment_isfinal'),
    ]

    operations = [
    ]
