# Generated by Django 3.1.7 on 2021-04-04 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_developer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_change_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='Name Change Count'),
        ),
    ]
