# Generated by Django 3.1.4 on 2021-04-19 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_team_name_change_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.PositiveSmallIntegerField(choices=[(1, 'Task Create'), (2, 'Task Edit'), (3, 'Task Submit'), (4, 'Task Comment'), (5, 'Task Final Comment'), (6, 'Task Creation Accept'), (7, 'Task Creation No Vote'), (8, 'Task Creation Request Change'), (9, 'Task Submission Accept'), (10, 'Task Submission No Vote'), (11, 'Task Submission Request Change'), (12, 'Task Reject')], default=0, verbose_name='Vote Type')),
                ('action_description', models.CharField(max_length=256, verbose_name='Action Description')),
                ('action_datetime', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Brief task name')),
                ('description', models.TextField(verbose_name='Description')),
                ('due', models.DateField(verbose_name='Due Date')),
                ('priority', models.PositiveSmallIntegerField(choices=[(3, 'Urgent'), (2, 'Planned'), (1, 'Low')], verbose_name='Priority')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(3, 'Difficult'), (2, 'Normal'), (1, 'Easy')], verbose_name='Difficulty')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('action_record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.actionrecord')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.developer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.task')),
            ],
        ),
    ]
