# Generated by Django 3.1.4 on 2021-04-17 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_team_name_change_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.PositiveSmallIntegerField(choices=[(1, 'Task Create'), (2, 'Task Edit'), (3, 'Task Submit'), (4, 'Task Comment'), (5, 'Task Final Comment'), (6, 'Task Accept'), (7, 'Task No Vote'), (8, 'Task Request Change'), (9, 'Task Reject')], default=0, verbose_name='Vote Type')),
                ('action_description', models.CharField(max_length=256, verbose_name='Action Description')),
                ('action_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
