# Generated by Django 3.1.4 on 2021-04-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_actionrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionrecord',
            old_name='actor_id',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='actionrecord',
            old_name='object_id',
            new_name='object',
        ),
    ]
