# Generated by Django 3.1.4 on 2021-05-16 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_task_datetime_fields_modified_added_new_datetimefields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creation_approved_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='submission_approved_on',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Completed on'),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Is Valid'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Task Create'), (2, 'Task Edit'), (3, 'Task Submit'), (4, 'Task Comment'), (5, 'Task Final Comment'), (6, 'Task Creation Accept'), (7, 'Task Status Change To Working On It'), (8, 'Task Creation Request Change'), (9, 'Task Submission Accept'), (10, 'Task Status Change To Waiting For Review'), (11, 'Task Submission Request Change'), (12, 'Task Reject')], default=0, verbose_name='Vote Type'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Brief task name'),
        ),
        migrations.AlterField(
            model_name='taskdifference',
            name='action_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.actionrecord'),
        ),
        migrations.AlterField(
            model_name='taskdifference',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.developer'),
        ),
        migrations.AlterField(
            model_name='taskdifference',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.task'),
        ),
    ]
