# Generated by Django 3.1.4 on 2021-04-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_auto_20210417_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrecord',
            name='action_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.task'),
        ),
        migrations.CreateModel(
            name='TaskDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Brief task name')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.PositiveSmallIntegerField(choices=[(3, 'Urgent'), (2, 'Planned'), (1, 'Low')], verbose_name='Priority')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(3, 'Difficult'), (2, 'Normal'), (1, 'Easy')], verbose_name='Difficulty')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('action_record_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.actionrecord')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.developer')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.task')),
            ],
        ),
    ]
