# Generated by Django 3.1.4 on 2021-05-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20210429_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointpool',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.course'),
        ),
    ]
