# Generated by Django 3.1.4 on 2021-04-25 14:13

from django.db import migrations, models
import django.utils.timezone
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210424_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='valid',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, validators=[tasks.models.past_date_validator], verbose_name='Completed on'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, validators=[tasks.models.past_date_validator], verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='creation_approved_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, validators=[tasks.models.past_date_validator], verbose_name='Creation approved on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='submission_approved_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, validators=[tasks.models.past_date_validator], verbose_name='Submission approved on'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Task title'),
        ),
    ]
