# Generated by Django 3.1.4 on 2021-04-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210418_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdifference',
            old_name='action_record_id',
            new_name='action_record',
        ),
        migrations.RenameField(
            model_name='taskdifference',
            old_name='task_id',
            new_name='task',
        ),
    ]
