# Generated by Django 3.1.4 on 2021-05-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_notification_table_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='team',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='tasks.task'),
        ),
    ]
