# Generated by Django 3.1.4 on 2021-05-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_graphintervals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphintervals',
            name='task',
        ),
        migrations.RemoveField(
            model_name='pointpool',
            name='team',
        ),
        migrations.AlterField(
            model_name='pointpool',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.course'),
        ),
        migrations.AlterField(
            model_name='pointpool',
            name='developer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.developer'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.developer'),
        ),
    ]
