# Generated by Django 3.1.4 on 2021-05-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20210508_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointpool',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.course'),
        ),
    ]
