# Generated by Django 3.1.4 on 2021-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_renamed_all_auto_now_date_fields_name_to_created_on'),
        ('tasks', '0015_removed_team_added_related_task_to_notifications'),
    ]

    operations = [
    ]
