# Generated by Django 3.0.2 on 2020-11-27 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_auto_20200303_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Review'), (2, 'Working on it'), (3, 'Waiting for review'), (4, 'Waiting for supervisor grade'), (5, 'Rejected'), (6, 'Accepted')], default=1, verbose_name='Status'),
        ),
    ]
