# Generated by Django 3.1.4 on 2021-05-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_0015_and_0012_renamed_all_auto_now_migration_merge'),
        ('tasks', '0012_pointpool_graphintervals_created_task_datetime_fields_modified'),
    ]

    operations = [
    ]
