# Generated by Django 3.1.4 on 2021-05-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_merge_20210522_1805'),
        ('tasks', '0012_auto_20210522_1917'),
    ]

    operations = [
    ]
