# Generated by Django 3.1.4 on 2021-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20210522_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='taskdifference',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
    ]
