# Generated by Django 3.1.4 on 2021-05-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20210522_2144'),
        ('tasks', '0012_auto_20210514_2120'),
    ]

    operations = [
    ]
