# Generated by Django 3.1.4 on 2021-05-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_task_last_modified_added_and_task_difference_actionrecord_created'),
        ('tasks', '0012_developer_supervisor_photo_url_and_actionrecord_modified'),
    ]

    operations = [
    ]
