# Generated by Django 3.1.4 on 2021-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_merge_20210522_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='photo_url',
            field=models.CharField(blank=True, max_length=2038, null=True, verbose_name='Photo URL:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Task title'),
        ),
    ]
