# Generated by Django 3.1.4 on 2021-05-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20210524_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='response_to',
        ),
    ]
