# Generated by Django 3.1.4 on 2021-05-24 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20210524_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Section'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'section'), name='Course section constraint'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='Milestone course constraint'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='Course team name constraint'),
        ),
    ]
