# Generated by Django 3.1.4 on 2021-05-28 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20210524_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='response_to',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default=1, max_length=256, verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Spring'), (1, 'Winter')], default=1, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020, verbose_name='Year'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course', 'section', 'year', 'term', 'section'), name='Course unique constraint'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='Milestone course constraint'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='Course team name constraint'),
        ),
    ]
