# Generated by Django 3.1.4 on 2021-05-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_comment_response_to'),
        ('tasks', '0022_section_and_constraints'),
    ]

    operations = [
    ]
