# Generated by Django 3.1.4 on 2021-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_response_to_and_course_fields_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='photo_url',
            field=models.CharField(blank=True, max_length=2038, null=True, verbose_name='Photo URL:'),
        ),
    ]
